### ISSUE TITLE
Document Trust-store config

### ISSUE THREAD

**Issue by robmoffat** [finos/symphony-java-toolkit#55]
Something like this: 

```
symphony: 
  trust-store:
    location:  classpath:/some-file.crt
    type: PEMS / JKS / PKCS12
    password: optional
```
